language: ruby

# Container based: faster
sudo: false

before_script:

rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.1

script:
  - script/ci/travis/install-gem-ci.rb
  - bundle exec rake unit
  - rake install
  - rake integration:ruby
  - rake integration:page-object-model
  - rake integration:cli

notifications:
  email:
    recipients:
      - joshua.moody@xamarin.com
      - tobias.roikjer@xamarin.com
    on_success: never
    on_failure: always
