<%

APP = ENV['CAL_APP'] || File.expand_path("./CalSmoke-cal.app")
IPA = ENV['CAL_APP'] || File.expand_path("./CalSmoke-cal.ipa")

DEVICE="193688959205dc7eb48d603c558ede919ad8dd0d"
ENDPOINT="http://denis.local:37265"

SIX_PLUS="iPhone 6 Plus (8.4 Simulator)"
IPAD_RETINA="iPad Retina (8.4 Simulator)"

if ENV["USER"] == "jenkins"
  formatter = "progress"
else
  formatter = "Slowhandcuke::Formatter"
end

%>

verbose: CAL_DEBUG=1
formatter: -f <%= formatter %>

# Launch on default simulator.
simulator_vars: CAL_APP=<%= APP %> #CAL_DEVICE_ID="iPad Retina (8.4 Simulator)"
simulator_tags: --tags ~@device_only
default:        -p simulator_vars -p simulator_tags -p formatter

# Launch on device.
device_vars:  CAL_APP=<%= IPA %> CAL_DEVICE_ID=<%= DEVICE %> CAL_ENDPOINT=<%= ENDPOINT %>
device_tags:  --tags ~@simulator_only
device:       -p device_vars -p device_tags -p formatter

