<%

APP = ENV['CAL_APP'] || File.expand_path("./CalSmoke-cal.app")
IPA = ENV['CAL_APP'] || File.expand_path("./CalSmoke-cal.ipa")

if ENV["USER"] == "jenkins"
  formatter = "progress"
else
  formatter = "Slowhandcuke::Formatter"
end

%>

verbose: CAL_DEBUG=1
formatter: -f <%= formatter %>

# Launch on default simulator.
default: CAL_APP=<%= APP %> -p formatter

# Launch on device.
device:  CAL_APP=<%= IPA %> -p formatter
