<%

APP = ENV['CAL_APP'] || File.expand_path("features/prebuilt/wordpress_ios.app")
APK = ENV['CAL_APP'] || File.expand_path("features/prebuilt/wordpress_android.apk")

%>

# Platform
android: CAL_APP=<%= APK %> PLATFORM=android -r features
ios:     CAL_APP=<%= APP %> PLATFORM=ios -r features
