<%

APP = ENV['CAL_APP'] || File.expand_path("binaries/wordpress_ios.app")
APK = ENV['CAL_APP'] || File.expand_path("binaries/wordpress_android.apk")

%>

# Platform
android: CAL_APP=<%= APK %> PLATFORM=android -r features --tags ~@ios
ios:     CAL_APP=<%= APP %> PLATFORM=ios -r features --tags ~@android
